language: node_js
node_js:
  - "node"
install:
  - npm ci
script:
  - npm run test
  - npm run test:cov
after_success:
  - bash <(curl -s https://codecov.io/bash)
branches:
  only:
    - master
    - next
cache:
  directories:
    - "$HOME/.npm"
notifications:
  email: false
